# Copyright 2026 Jeremy Edwards
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-linux:
    runs-on: ["self-hosted", "linux", "large"]
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6
      - name: Setup Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Build
        run: make build -j$(nproc)
      - name: Test
        run: make test
      - name: Test (Deflake)
        run: make test-deflake
      - name: Zip binaries
        run: cd bin/go && zip -qr9 ../../linux-build-bin.zip . -x 'windows_*' -x 'windows_*/*'
      - name: Upload binaries
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-bin
          retention-days: 1
          path: linux-build-bin.zip
  build-windows:
    runs-on: ["self-hosted", "windows"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Build
        run: make all -j8
      - name: Test
        run: make test
      - name: Test (Race Test)
        run: make GO_TEST_COUNT=5 test-deflake
      - name: Zip binaries
        run: |
          cd bin/go
          zip -qr9 ../../windows-build-bin.zip windows_*
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-bin
          retention-days: 1
          path: windows-build-bin.zip
  package:
    needs: [build-linux, build-windows]
    runs-on: ["self-hosted", "linux"]
    permissions:
      actions: write
    steps:
      - name: Download Linux binaries
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build-bin
      - name: Download Windows binaries
        uses: actions/download-artifact@v4
        with:
          name: windows-build-bin
      - name: Extract binaries
        run: |
          mkdir -p bin/go
          unzip -oq linux-build-bin.zip -d bin/go
          unzip -oq windows-build-bin.zip -d bin/go
      - name: Zip binaries
        run: cd bin/go && zip -qr9 ../../ufs-binaries.zip .
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: ufs-binaries
          path: ufs-binaries.zip
      - name: Delete intermediate artifacts
        # https://github.com/GeekyEggo/delete-artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            linux-build-bin
            windows-build-bin
